/*
 * configuration.c
 *
 *  Created on: 19 Dec 2020
 *      Author: HP
 */

#include "DIO_REG.h"


Config_PINS arr[no_pins]={{OUTPUT,PORTC0},{OUTPUT,PORTC1},{OUTPUT,PORTC2},{OUTPUT,PORTC3},{OUTPUT,PORTC4},{OUTPUT,PORTC5},{OUTPUT,PORTC6},{OUTPUT,PORTC7}
                             ,{OUTPUT,PORTA0},{OUTPUT,PORTA1},{OUTPUT,PORTA2},{PULL_UP,PORTD0},{PULL_UP,PORTD1},{PULL_UP,PORTD2},{PULL_UP,PORTD3},{OUTPUT,PORTD4},{OUTPUT,PORTD5},{OUTPUT,PORTD6},{OUTPUT,PORTD7}};
